wx:
  ma:
    configs:
      - appid: your_app_id  # 替换为实际值
        secret: your_app_secret    # 替换为实际值
        token: verify_token         # 消息校验 Token（非必填）
        aesKey: encryption_key     # 消息加密密钥（非必填）

app:
  id-generator:
    hmac-secret: your_hamc_secret # 建议使用环境变量注入
    snowflake:
      worker-id: ${SNOWFLAKE_WORKER_ID:0}
      datacenter-id: ${SNOWFLAKE_DATACENTER_ID:0}

spring:
  datasource:
    url: jdbc:mysql://host:port/your_database?useSSL=false&serverTimezone=UTC
    username: your_mysql_username
    password: your_mysql_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate # 开发环境可用，生产环境改为 validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB # 设置单个上传文件的最大大小。如果上传的文件超过了这个大小限制，Spring Boot 会抛出 MaxUploadSizeExceededException 异常。
      max-request-size: 10MB # 设置整个 HTTP 请求的最大大小。这包括所有上传的文件以及其他的请求数据。如果整个请求的大小超过了这个限制，Spring Boot 也会抛出 MaxUploadSizeExceededException 异常。

jwt:
  secret: your_secret
  expiration: expire_time